# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/decisionhub
spring.datasource.username=postgres
spring.datasource.password=myth
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLXNwcmluZy1ib290
jwt.expiration=86400000