spring.profiles.active=local

# JWT Configuration
jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLXNwcmluZy1ib290}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Database Seeder Configuration (Uses Env Vars for Prod, Fallbacks for Local)
app.admin.email=${ADMIN_EMAIL:admin@gmail.com}
app.admin.password=${ADMIN_PASSWORD:admin123}
